spring:
  application:
    name: DoDo


---
spring:
  profiles: local
  datasource:

    #url: jdbc:h2:mem:testdb;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  security:
    user:
      name: user
      password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
